import {
  AuditLogEntry,
  AuthUser,
  GoldenCustomer,
  MatchConfig,
  Opportunity,
  OpportunityRule,
  ReviewItem,
} from '../types';

export const INITIAL_USERS: AuthUser[] = [
  {
    id: 'user-rm-1',
    email: 'rm1@firm.com',
    name: 'Arjun Mehta (RM)',
    role: 'rm',
    rmId: 'rm1',
    teamName: 'North Metro Wealth & Retail',
    token: 'jwt_rm_arjun_token_991823',
  },
  {
    id: 'user-manager-1',
    email: 'manager@firm.com',
    name: 'Sunita Deshmukh (Branch Manager)',
    role: 'manager',
    teamName: 'Western & Northern Regional Division',
    token: 'jwt_mgr_sunita_token_481029',
  },
  {
    id: 'user-admin-1',
    email: 'admin@firm.com',
    name: 'Devraj Kapoor (Data Admin)',
    role: 'admin',
    teamName: 'Core Enterprise Intelligence & Governance',
    token: 'jwt_adm_devraj_token_773912',
  },
];

export const INITIAL_MATCH_CONFIG: MatchConfig = {
  weights: {
    pan: 40,
    mobile: 25,
    email: 15,
    dob: 10,
    name: 7,
    city: 3,
  },
  autoMergeThreshold: 85,
  manualReviewThreshold: 60,
  lastUpdated: '2026-08-20T14:32:00Z',
  updatedBy: 'admin@firm.com',
};

export const INITIAL_OPPORTUNITY_RULES: OpportunityRule[] = [
  {
    id: 'rule-insurance-cross-sell',
    product: 'insurance',
    title: 'Insurance Protection Cross-sell',
    enabled: true,
    conditions: {
      minEquityBalance: 500000, // ₹5L
      minMfBalance: 500000, // ₹5L
      minTotalRelationshipValue: 1000000, // ₹10L
      targetMissingProduct: 'insurance',
      minScore: 65,
      potentialValueFormula: '10% of annual investable surplus',
    },
    description: 'Triggered when client has >= ₹5L in Equity AND >= ₹5L in Mutual Funds with zero active term or health coverage in group records.',
  },
  {
    id: 'rule-wealth-upgrade',
    product: 'wealth',
    title: 'Private Wealth Management Advisory',
    enabled: true,
    conditions: {
      minEquityBalance: 500000,
      minMfBalance: 800000,
      minTotalRelationshipValue: 2000000, // ₹20L
      requiredSegment: ['HNI', 'Ultra HNI', 'Affluent Prime'],
      targetMissingProduct: 'wealth',
      minScore: 75,
      potentialValueFormula: 'Advisory AUM potential: ₹20L - ₹50L',
    },
    description: 'Identifies high-net-worth customers across retail silos holding > ₹20L portfolio without a dedicated private banker.',
  },
  {
    id: 'rule-las-credit',
    product: 'loans',
    title: 'Loan Against Securities (LAS) Overdraft',
    enabled: true,
    conditions: {
      minTotalRelationshipValue: 1500000,
      targetMissingProduct: 'loans',
      minScore: 70,
      potentialValueFormula: '50% of Equity + MF valuation as instant line',
    },
    description: 'Offers pre-approved liquidity line against equity & mutual fund collateral with instant digital lien mark.',
  },
  {
    id: 'rule-mf-sip',
    product: 'mf',
    title: 'Systematic Investment Plan (MF)',
    enabled: true,
    conditions: {
      minTotalRelationshipValue: 200000,
      targetMissingProduct: 'mf',
      minScore: 60,
      potentialValueFormula: '₹25,000 monthly SIP potential',
    },
    description: 'Recommended for customers holding single-asset products (e.g. Loans or Equity only) to build balanced recurring wealth.',
  },
  {
    id: 'rule-equity-demat',
    product: 'equity',
    title: 'Direct Equity & IPO Trading Demat',
    enabled: true,
    conditions: {
      minTotalRelationshipValue: 500000,
      targetMissingProduct: 'equity',
      minScore: 65,
      potentialValueFormula: 'Active brokerage pipeline',
    },
    description: 'Targets clients with active mutual fund investments who do not have an active direct equity brokerage account.',
  },
];

export const INITIAL_CUSTOMERS: GoldenCustomer[] = [
  {
    goldenId: 'CUST0001',
    name: 'Rahul Sharma',
    pan: 'ABCDE1234F',
    rawPan: 'ABCDE1234F',
    mobile: '9876543210',
    rawMobile: '9876543210',
    email: 'rahul@gmail.com',
    dob: '1998-05-12',
    city: 'Mumbai',
    segment: 'HNI',
    rmId: 'rm1',
    rmName: 'Arjun Mehta',
    linkedSources: ['equity', 'mf', 'loans'],
    totalRelationshipValue: 2400000, // ₹24 Lakhs
    matchConfidence: 84,
    matchDecision: 'manual_review',
    hasOpportunity: true,
    opportunityCount: 2,
    attributeConflicts: [
      {
        field: 'Email Address',
        selectedValue: 'rahul@gmail.com',
        selectedSource: 'equity',
        precedenceBadge: 'Equity Primary (Verified KYC)',
        conflictingValues: [
          { value: 'rahul123@gmail.com', source: 'mf' },
          { value: 'rahul.work@gmail.com', source: 'insurance' },
        ],
        flaggedForReview: true,
        overrideReason: 'Equity record passed 2FA biometric verification on 2026-05-10',
      },
    ],
    productHoldings: [
      {
        product: 'equity',
        system: 'equity',
        accountId: 'EQ-889021',
        balance: 800000, // ₹8L
        active: true,
        lastActivityDate: '2026-08-14',
        schemeOrPlanName: 'Pro Trader Demat + Cash Equities',
      },
      {
        product: 'mf',
        system: 'mf',
        accountId: 'MF-440192',
        balance: 1200000, // ₹12L
        active: true,
        lastActivityDate: '2026-08-10',
        schemeOrPlanName: 'Large & Midcap Growth Portfolio (4 Folios)',
      },
      {
        product: 'loans',
        system: 'loans',
        accountId: 'LN-109284',
        balance: 400000, // ₹4L
        active: true,
        lastActivityDate: '2026-07-28',
        schemeOrPlanName: 'Secured Personal Line of Credit',
      },
    ],
    evidence: [
      {
        field: 'PAN Number',
        weight: 40,
        valueA: 'ABCDE1234F',
        valueB: 'ABCDE1234F',
        result: 'match',
        explanation: 'Exact 10-character PAN match across source silos',
      },
      {
        field: 'Mobile Number',
        weight: 25,
        valueA: '9876543210',
        valueB: '9876543210',
        result: 'match',
        explanation: 'Standardized 10-digit mobile number matches exactly',
      },
      {
        field: 'Email Address',
        weight: 15,
        valueA: 'rahul@gmail.com',
        valueB: 'rahul123@gmail.com',
        result: 'conflict',
        explanation: 'Conflicting emails: Primary rahul@ vs secondary rahul123@',
      },
      {
        field: 'Date of Birth',
        weight: 10,
        valueA: '1998-05-12',
        valueB: '1998-05-12',
        result: 'match',
        explanation: 'Standardized ISO date matches exactly (12 May 1998)',
      },
      {
        field: 'Customer Name',
        weight: 7,
        valueA: 'Rahul Sharma',
        valueB: 'Rahul S Sharma',
        result: 'partial',
        similarity: 93,
        explanation: 'Jaro-Winkler 93% match (middle initial expansion)',
      },
      {
        field: 'City & Location',
        weight: 3,
        valueA: 'Mumbai',
        valueB: 'Mumbai',
        result: 'match',
        explanation: 'Same normalized metro jurisdiction',
      },
    ],
    sourceLineage: [
      {
        system: 'equity',
        sourceCustomerId: 'EQ101',
        rawName: 'Rahul Sharma',
        normalizedName: 'rahul sharma',
        rawMobile: '+91-9876543210',
        normalizedMobile: '9876543210',
        rawEmail: 'rahul@gmail.com',
        normalizedEmail: 'rahul@gmail.com',
        rawPan: 'ABCDE1234F',
        normalizedPan: 'ABCDE1234F',
        rawDob: '12/05/1998',
        normalizedDob: '1998-05-12',
        rawCity: 'MUMBAI - BKC',
        normalizedCity: 'Mumbai',
        segment: 'HNI Trader',
        balance: 800000,
        lastActive: '2026-08-14',
      },
      {
        system: 'mf',
        sourceCustomerId: 'MF501',
        rawName: 'Rahul S Sharma',
        normalizedName: 'rahul s sharma',
        rawMobile: '09876543210',
        normalizedMobile: '9876543210',
        rawEmail: 'rahul123@gmail.com',
        normalizedEmail: 'rahul123@gmail.com',
        rawPan: 'ABCDE1234F',
        normalizedPan: 'ABCDE1234F',
        rawDob: '1998-05-12',
        normalizedDob: '1998-05-12',
        rawCity: 'Mumbai',
        normalizedCity: 'Mumbai',
        segment: 'Wealth Investor',
        balance: 1200000,
        lastActive: '2026-08-10',
      },
      {
        system: 'loans',
        sourceCustomerId: 'LN802',
        rawName: 'RAHUL SHARMA',
        normalizedName: 'rahul sharma',
        rawMobile: '98765 43210',
        normalizedMobile: '9876543210',
        rawEmail: 'rahul@gmail.com',
        normalizedEmail: 'rahul@gmail.com',
        rawPan: 'ABCDE1234F',
        normalizedPan: 'ABCDE1234F',
        rawDob: '12-May-1998',
        normalizedDob: '1998-05-12',
        rawCity: 'Mumbai West',
        normalizedCity: 'Mumbai',
        segment: 'Prime Retail',
        balance: 400000,
        lastActive: '2026-07-28',
      },
    ],
  },
  {
    goldenId: 'CUST0002',
    name: 'Priya Patel',
    pan: 'PQRPA7788K',
    rawPan: 'PQRPA7788K',
    mobile: '9823456789',
    rawMobile: '9823456789',
    email: 'priya.patel@outlook.com',
    dob: '1991-03-24',
    city: 'Ahmedabad',
    segment: 'Affluent Prime',
    rmId: 'rm1',
    rmName: 'Arjun Mehta',
    linkedSources: ['mf', 'insurance'],
    totalRelationshipValue: 800000, // ₹8L
    matchConfidence: 78,
    matchDecision: 'manual_review',
    hasOpportunity: true,
    opportunityCount: 2,
    attributeConflicts: [],
    productHoldings: [
      {
        product: 'mf',
        system: 'mf',
        accountId: 'MF-339182',
        balance: 650000, // ₹6.5L
        active: true,
        lastActivityDate: '2026-08-01',
        schemeOrPlanName: 'Tax Saver ELSS + Flexi Cap',
      },
      {
        product: 'insurance',
        system: 'insurance',
        accountId: 'INS-991024',
        balance: 150000, // ₹1.5L
        active: true,
        lastActivityDate: '2026-07-15',
        schemeOrPlanName: 'Term Shield Life 1Cr Coverage',
      },
    ],
    evidence: [
      {
        field: 'PAN Number',
        weight: 40,
        valueA: 'PQRPA7788K',
        valueB: null,
        result: 'missing',
        explanation: 'PAN absent in legacy Insurance insurance archive (weaker identifier mode)',
      },
      {
        field: 'Mobile Number',
        weight: 25,
        valueA: '9823456789',
        valueB: '9823456789',
        result: 'match',
        explanation: 'Exact mobile number match',
      },
      {
        field: 'Email Address',
        weight: 15,
        valueA: 'priya.patel@outlook.com',
        valueB: 'priya.patel@outlook.com',
        result: 'match',
        explanation: 'Verified corporate domain email match',
      },
      {
        field: 'Date of Birth',
        weight: 10,
        valueA: '1991-03-24',
        valueB: '1991-03-24',
        result: 'match',
        explanation: 'Exact matching DOB',
      },
      {
        field: 'Customer Name',
        weight: 7,
        valueA: 'Priya Patel',
        valueB: 'Priya N Patel',
        result: 'partial',
        similarity: 95,
        explanation: 'Jaro-Winkler 95% name match',
      },
      {
        field: 'City & Location',
        weight: 3,
        valueA: 'Ahmedabad',
        valueB: 'Ahmedabad',
        result: 'match',
        explanation: 'Exact city match',
      },
    ],
    sourceLineage: [
      {
        system: 'mf',
        sourceCustomerId: 'MF204',
        rawName: 'Priya Patel',
        normalizedName: 'priya patel',
        rawMobile: '+91-9823456789',
        normalizedMobile: '9823456789',
        rawEmail: 'priya.patel@outlook.com',
        normalizedEmail: 'priya.patel@outlook.com',
        rawPan: 'PQRPA7788K',
        normalizedPan: 'PQRPA7788K',
        rawDob: '1991-03-24',
        normalizedDob: '1991-03-24',
        rawCity: 'Ahmedabad',
        normalizedCity: 'Ahmedabad',
        segment: 'Affluent Prime',
        balance: 650000,
        lastActive: '2026-08-01',
      },
      {
        system: 'insurance',
        sourceCustomerId: 'INS991',
        rawName: 'Priya N Patel',
        normalizedName: 'priya n patel',
        rawMobile: '9823456789',
        normalizedMobile: '9823456789',
        rawEmail: 'priya.patel@outlook.com',
        normalizedEmail: 'priya.patel@outlook.com',
        rawDob: '24-03-1991',
        normalizedDob: '1991-03-24',
        rawCity: 'Ahmedabad (SG Highway)',
        normalizedCity: 'Ahmedabad',
        segment: 'Policyholder',
        balance: 150000,
        lastActive: '2026-07-15',
      },
    ],
  },
  {
    goldenId: 'CUST0004',
    name: 'Ananya Sen',
    pan: 'BKUPS4321A',
    rawPan: 'BKUPS4321A',
    mobile: '9712345678',
    rawMobile: '9712345678',
    email: 'ananya.sen@acme.com',
    dob: '1985-07-19',
    city: 'Bengaluru',
    segment: 'Ultra HNI',
    rmId: 'rm2',
    rmName: 'Kavita Rao',
    linkedSources: ['equity', 'mf', 'wealth'],
    totalRelationshipValue: 22500000, // ₹2.25 Crore
    matchConfidence: 98,
    matchDecision: 'auto_merge',
    hasOpportunity: true,
    opportunityCount: 1,
    attributeConflicts: [],
    productHoldings: [
      {
        product: 'equity',
        system: 'equity',
        accountId: 'EQ-100293',
        balance: 4500000, // ₹45L
        active: true,
        lastActivityDate: '2026-08-18',
        schemeOrPlanName: 'Institutional Direct Brokerage',
      },
      {
        product: 'mf',
        system: 'mf',
        accountId: 'MF-883921',
        balance: 6000000, // ₹60L
        active: true,
        lastActivityDate: '2026-08-17',
        schemeOrPlanName: 'PMS & Dynamic Asset Allocation',
      },
      {
        product: 'wealth',
        system: 'wealth',
        accountId: 'WL-330198',
        balance: 12000000, // ₹1.20 Cr
        active: true,
        lastActivityDate: '2026-08-19',
        schemeOrPlanName: 'Family Office Bespoke Advisory Mandate',
      },
    ],
    evidence: [
      {
        field: 'PAN Number',
        weight: 40,
        valueA: 'BKUPS4321A',
        valueB: 'BKUPS4321A',
        result: 'match',
        explanation: 'Perfect PAN alignment across institutional registries',
      },
      {
        field: 'Mobile Number',
        weight: 25,
        valueA: '9712345678',
        valueB: '9712345678',
        result: 'match',
        explanation: 'Exact mobile number match',
      },
      {
        field: 'Email Address',
        weight: 15,
        valueA: 'ananya.sen@acme.com',
        valueB: 'ananya.sen@acme.com',
        result: 'match',
        explanation: 'Verified corporate domain email match',
      },
      {
        field: 'Date of Birth',
        weight: 10,
        valueA: '1985-07-19',
        valueB: '1985-07-19',
        result: 'match',
        explanation: 'Exact matching DOB',
      },
      {
        field: 'Customer Name',
        weight: 7,
        valueA: 'Ananya Sen',
        valueB: 'Ananya Sen',
        result: 'match',
        similarity: 100,
        explanation: '100% exact name match',
      },
      {
        field: 'City & Location',
        weight: 3,
        valueA: 'Bengaluru',
        valueB: 'Bengaluru',
        result: 'match',
        explanation: 'Bengaluru Tech Hub',
      },
    ],
    sourceLineage: [
      {
        system: 'equity',
        sourceCustomerId: 'EQ901',
        rawName: 'Ananya Sen',
        normalizedName: 'ananya sen',
        rawMobile: '9712345678',
        normalizedMobile: '9712345678',
        rawEmail: 'ananya.sen@acme.com',
        normalizedEmail: 'ananya.sen@acme.com',
        rawPan: 'BKUPS4321A',
        normalizedPan: 'BKUPS4321A',
        rawDob: '1985-07-19',
        normalizedDob: '1985-07-19',
        rawCity: 'Bengaluru',
        normalizedCity: 'Bengaluru',
        segment: 'Ultra HNI',
        balance: 4500000,
        lastActive: '2026-08-18',
      },
      {
        system: 'mf',
        sourceCustomerId: 'MF902',
        rawName: 'Ananya Sen',
        normalizedName: 'ananya sen',
        rawMobile: '+91-9712345678',
        normalizedMobile: '9712345678',
        rawEmail: 'ananya.sen@acme.com',
        normalizedEmail: 'ananya.sen@acme.com',
        rawPan: 'BKUPS4321A',
        normalizedPan: 'BKUPS4321A',
        rawDob: '1985-07-19',
        normalizedDob: '1985-07-19',
        rawCity: 'Bengaluru - Whitefield',
        normalizedCity: 'Bengaluru',
        segment: 'Ultra HNI',
        balance: 6000000,
        lastActive: '2026-08-17',
      },
      {
        system: 'wealth',
        sourceCustomerId: 'WL903',
        rawName: 'Ananya Sen',
        normalizedName: 'ananya sen',
        rawMobile: '9712345678',
        normalizedMobile: '9712345678',
        rawEmail: 'ananya.sen@acme.com',
        normalizedEmail: 'ananya.sen@acme.com',
        rawPan: 'BKUPS4321A',
        normalizedPan: 'BKUPS4321A',
        rawDob: '1985-07-19',
        normalizedDob: '1985-07-19',
        rawCity: 'Bengaluru',
        normalizedCity: 'Bengaluru',
        segment: 'Ultra HNI',
        balance: 12000000,
        lastActive: '2026-08-19',
      },
    ],
  },
  {
    goldenId: 'CUST0005',
    name: 'Amit Verma',
    pan: 'MNOPA5678Z',
    rawPan: 'MNOPA5678Z',
    mobile: '9845012345',
    rawMobile: '9845012345',
    email: 'amit.verma@fintech.io',
    dob: '1988-11-04',
    city: 'Delhi NCR',
    segment: 'HNI',
    rmId: 'rm1',
    rmName: 'Arjun Mehta',
    linkedSources: ['equity', 'mf'],
    totalRelationshipValue: 3300000, // ₹33L (Equity ₹15L + MF ₹18L)
    matchConfidence: 96,
    matchDecision: 'auto_merge',
    hasOpportunity: true,
    opportunityCount: 2,
    attributeConflicts: [],
    productHoldings: [
      {
        product: 'equity',
        system: 'equity',
        accountId: 'EQ-449102',
        balance: 1500000, // ₹15L
        active: true,
        lastActivityDate: '2026-08-16',
        schemeOrPlanName: 'Alpha Momentum Trading Account',
      },
      {
        product: 'mf',
        system: 'mf',
        accountId: 'MF-670192',
        balance: 1800000, // ₹18L
        active: true,
        lastActivityDate: '2026-08-12',
        schemeOrPlanName: 'Global Index Feeder + MidCap Fund',
      },
    ],
    evidence: [
      {
        field: 'PAN Number',
        weight: 40,
        valueA: 'MNOPA5678Z',
        valueB: 'MNOPA5678Z',
        result: 'match',
        explanation: 'PAN matches',
      },
      {
        field: 'Mobile Number',
        weight: 25,
        valueA: '9845012345',
        valueB: '9845012345',
        result: 'match',
        explanation: 'Mobile matches',
      },
      {
        field: 'Email Address',
        weight: 15,
        valueA: 'amit.verma@fintech.io',
        valueB: 'amit.verma@fintech.io',
        result: 'match',
        explanation: 'Email matches',
      },
      {
        field: 'Date of Birth',
        weight: 10,
        valueA: '1988-11-04',
        valueB: '1988-11-04',
        result: 'match',
        explanation: 'DOB matches',
      },
      {
        field: 'Customer Name',
        weight: 7,
        valueA: 'Amit Verma',
        valueB: 'Amit Verma',
        result: 'match',
        similarity: 100,
      },
      {
        field: 'City & Location',
        weight: 3,
        valueA: 'Delhi NCR',
        valueB: 'Gurugram',
        result: 'match',
        explanation: 'Mapped to NCR territory',
      },
    ],
    sourceLineage: [
      {
        system: 'equity',
        sourceCustomerId: 'EQ301',
        rawName: 'Amit Verma',
        normalizedName: 'amit verma',
        rawMobile: '9845012345',
        normalizedMobile: '9845012345',
        rawEmail: 'amit.verma@fintech.io',
        normalizedEmail: 'amit.verma@fintech.io',
        rawPan: 'MNOPA5678Z',
        normalizedPan: 'MNOPA5678Z',
        rawDob: '1988-11-04',
        normalizedDob: '1988-11-04',
        rawCity: 'Delhi NCR',
        normalizedCity: 'Delhi NCR',
        segment: 'HNI',
        balance: 1500000,
        lastActive: '2026-08-16',
      },
      {
        system: 'mf',
        sourceCustomerId: 'MF302',
        rawName: 'Amit Verma',
        normalizedName: 'amit verma',
        rawMobile: '+919845012345',
        normalizedMobile: '9845012345',
        rawEmail: 'amit.verma@fintech.io',
        normalizedEmail: 'amit.verma@fintech.io',
        rawPan: 'MNOPA5678Z',
        normalizedPan: 'MNOPA5678Z',
        rawDob: '1988-11-04',
        normalizedDob: '1988-11-04',
        rawCity: 'Gurugram',
        normalizedCity: 'Delhi NCR',
        segment: 'HNI',
        balance: 1800000,
        lastActive: '2026-08-12',
      },
    ],
  },
  {
    goldenId: 'CUST0006',
    name: 'Sneha Kapoor',
    pan: 'KLMNA9012Q',
    rawPan: 'KLMNA9012Q',
    mobile: '9819876543',
    rawMobile: '9819876543',
    email: 'sneha.k@gmail.com',
    dob: '1993-09-30',
    city: 'Pune',
    segment: 'Retail Prime',
    rmId: 'rm2',
    rmName: 'Kavita Rao',
    linkedSources: ['loans', 'insurance'],
    totalRelationshipValue: 1350000, // ₹13.5L
    matchConfidence: 94,
    matchDecision: 'auto_merge',
    hasOpportunity: true,
    opportunityCount: 2,
    attributeConflicts: [],
    productHoldings: [
      {
        product: 'loans',
        system: 'loans',
        accountId: 'LN-554109',
        balance: 1200000, // ₹12L
        active: true,
        lastActivityDate: '2026-08-05',
        schemeOrPlanName: 'Auto Loan & Home Renovation Line',
      },
      {
        product: 'insurance',
        system: 'insurance',
        accountId: 'INS-229103',
        balance: 150000, // ₹1.5L
        active: true,
        lastActivityDate: '2026-07-20',
        schemeOrPlanName: 'Comprehensive Motor + Critical Illness Shield',
      },
    ],
    evidence: [
      {
        field: 'PAN Number',
        weight: 40,
        valueA: 'KLMNA9012Q',
        valueB: 'KLMNA9012Q',
        result: 'match',
      },
      {
        field: 'Mobile Number',
        weight: 25,
        valueA: '9819876543',
        valueB: '9819876543',
        result: 'match',
      },
      {
        field: 'Email Address',
        weight: 15,
        valueA: 'sneha.k@gmail.com',
        valueB: 'sneha.k@gmail.com',
        result: 'match',
      },
      {
        field: 'Date of Birth',
        weight: 10,
        valueA: '1993-09-30',
        valueB: '1993-09-30',
        result: 'match',
      },
      {
        field: 'Customer Name',
        weight: 7,
        valueA: 'Sneha Kapoor',
        valueB: 'Sneha Kapoor',
        result: 'match',
        similarity: 100,
      },
      {
        field: 'City & Location',
        weight: 3,
        valueA: 'Pune',
        valueB: 'Pune',
        result: 'match',
      },
    ],
    sourceLineage: [
      {
        system: 'loans',
        sourceCustomerId: 'LN441',
        rawName: 'Sneha Kapoor',
        normalizedName: 'sneha kapoor',
        rawMobile: '9819876543',
        normalizedMobile: '9819876543',
        rawEmail: 'sneha.k@gmail.com',
        normalizedEmail: 'sneha.k@gmail.com',
        rawPan: 'KLMNA9012Q',
        normalizedPan: 'KLMNA9012Q',
        rawDob: '1993-09-30',
        normalizedDob: '1993-09-30',
        rawCity: 'Pune - Viman Nagar',
        normalizedCity: 'Pune',
        segment: 'Retail Prime',
        balance: 1200000,
        lastActive: '2026-08-05',
      },
      {
        system: 'insurance',
        sourceCustomerId: 'INS442',
        rawName: 'Sneha Kapoor',
        normalizedName: 'sneha kapoor',
        rawMobile: '+91 98198 76543',
        normalizedMobile: '9819876543',
        rawEmail: 'sneha.k@gmail.com',
        normalizedEmail: 'sneha.k@gmail.com',
        rawPan: 'KLMNA9012Q',
        normalizedPan: 'KLMNA9012Q',
        rawDob: '1993-09-30',
        normalizedDob: '1993-09-30',
        rawCity: 'Pune',
        normalizedCity: 'Pune',
        segment: 'Retail Prime',
        balance: 150000,
        lastActive: '2026-07-20',
      },
    ],
  },
];

export const INITIAL_REVIEW_QUEUE: ReviewItem[] = [
  {
    id: 'REV-001',
    candidateName: 'Rahul Sharma',
    candidateGoldenId: 'CUST0001',
    sourceA: {
      system: 'equity',
      sourceCustomerId: 'EQ101',
      rawName: 'Rahul Sharma',
      normalizedName: 'rahul sharma',
      rawMobile: '+91-9876543210',
      normalizedMobile: '9876543210',
      rawEmail: 'rahul@gmail.com',
      normalizedEmail: 'rahul@gmail.com',
      rawPan: 'ABCDE1234F',
      normalizedPan: 'ABCDE1234F',
      rawDob: '12/05/1998',
      normalizedDob: '1998-05-12',
      rawCity: 'Mumbai BKC',
      normalizedCity: 'Mumbai',
      segment: 'HNI',
      balance: 800000,
      lastActive: '2026-08-14',
    },
    sourceB: {
      system: 'mf',
      sourceCustomerId: 'MF501',
      rawName: 'Rahul S Sharma',
      normalizedName: 'rahul s sharma',
      rawMobile: '09876543210',
      normalizedMobile: '9876543210',
      rawEmail: 'rahul123@gmail.com',
      normalizedEmail: 'rahul123@gmail.com',
      rawPan: 'ABCDE1234F',
      normalizedPan: 'ABCDE1234F',
      rawDob: '1998-05-12',
      normalizedDob: '1998-05-12',
      rawCity: 'Mumbai',
      normalizedCity: 'Mumbai',
      segment: 'Wealth Investor',
      balance: 1200000,
      lastActive: '2026-08-10',
    },
    confidence: 84,
    decision: 'pending',
    isDangerousConflict: false,
    evidence: [
      {
        field: 'PAN Number',
        weight: 40,
        valueA: 'ABCDE1234F',
        valueB: 'ABCDE1234F',
        result: 'match',
        explanation: 'Exact 10-character PAN match',
      },
      {
        field: 'Mobile Number',
        weight: 25,
        valueA: '9876543210',
        valueB: '9876543210',
        result: 'match',
        explanation: 'Exact 10-digit mobile match',
      },
      {
        field: 'Email Address',
        weight: 15,
        valueA: 'rahul@gmail.com',
        valueB: 'rahul123@gmail.com',
        result: 'conflict',
        explanation: 'Conflicting email values across silos',
      },
      {
        field: 'Date of Birth',
        weight: 10,
        valueA: '1998-05-12',
        valueB: '1998-05-12',
        result: 'match',
        explanation: 'Exact matching DOB',
      },
      {
        field: 'Customer Name',
        weight: 7,
        valueA: 'Rahul Sharma',
        valueB: 'Rahul S Sharma',
        result: 'partial',
        similarity: 93,
        explanation: 'Jaro-Winkler 93% similarity',
      },
      {
        field: 'City & Location',
        weight: 3,
        valueA: 'Mumbai BKC',
        valueB: 'Mumbai',
        result: 'match',
        explanation: 'Metro jurisdiction match',
      },
    ],
  },
  {
    id: 'REV-002',
    candidateName: 'Priya Patel',
    candidateGoldenId: 'CUST0002',
    sourceA: {
      system: 'mf',
      sourceCustomerId: 'MF204',
      rawName: 'Priya Patel',
      normalizedName: 'priya patel',
      rawMobile: '+91-9823456789',
      normalizedMobile: '9823456789',
      rawEmail: 'priya.patel@outlook.com',
      normalizedEmail: 'priya.patel@outlook.com',
      rawPan: 'PQRPA7788K',
      normalizedPan: 'PQRPA7788K',
      rawDob: '1991-03-24',
      normalizedDob: '1991-03-24',
      rawCity: 'Ahmedabad',
      normalizedCity: 'Ahmedabad',
      segment: 'Affluent Prime',
      balance: 650000,
      lastActive: '2026-08-01',
    },
    sourceB: {
      system: 'insurance',
      sourceCustomerId: 'INS991',
      rawName: 'Priya N Patel',
      normalizedName: 'priya n patel',
      rawMobile: '9823456789',
      normalizedMobile: '9823456789',
      rawEmail: 'priya.patel@outlook.com',
      normalizedEmail: 'priya.patel@outlook.com',
      rawDob: '24-03-1991',
      normalizedDob: '1991-03-24',
      rawCity: 'Ahmedabad (SG Highway)',
      normalizedCity: 'Ahmedabad',
      segment: 'Policyholder',
      balance: 150000,
      lastActive: '2026-07-15',
    },
    confidence: 78,
    decision: 'pending',
    isDangerousConflict: false,
    evidence: [
      {
        field: 'PAN Number',
        weight: 40,
        valueA: 'PQRPA7788K',
        valueB: null,
        result: 'missing',
        explanation: 'PAN absent in legacy Insurance policy record',
      },
      {
        field: 'Mobile Number',
        weight: 25,
        valueA: '9823456789',
        valueB: '9823456789',
        result: 'match',
      },
      {
        field: 'Email Address',
        weight: 15,
        valueA: 'priya.patel@outlook.com',
        valueB: 'priya.patel@outlook.com',
        result: 'match',
      },
      {
        field: 'Date of Birth',
        weight: 10,
        valueA: '1991-03-24',
        valueB: '1991-03-24',
        result: 'match',
      },
      {
        field: 'Customer Name',
        weight: 7,
        valueA: 'Priya Patel',
        valueB: 'Priya N Patel',
        result: 'partial',
        similarity: 95,
      },
      {
        field: 'City & Location',
        weight: 3,
        valueA: 'Ahmedabad',
        valueB: 'Ahmedabad',
        result: 'match',
      },
    ],
  },
  {
    id: 'REV-003',
    candidateName: 'Vikram Malhotra / Vikramaditya Rao',
    sourceA: {
      system: 'loans',
      sourceCustomerId: 'LN772',
      rawName: 'Vikram Malhotra',
      normalizedName: 'vikram malhotra',
      rawMobile: '9811223344',
      normalizedMobile: '9811223344',
      rawEmail: 'vikram.m@domain.com',
      normalizedEmail: 'vikram.m@domain.com',
      rawPan: 'ABCDE5555X',
      normalizedPan: 'ABCDE5555X',
      rawDob: '1982-01-15',
      normalizedDob: '1982-01-15',
      rawCity: 'Chandigarh',
      normalizedCity: 'Chandigarh',
      segment: 'Retail',
      balance: 900000,
      lastActive: '2026-07-10',
    },
    sourceB: {
      system: 'equity',
      sourceCustomerId: 'EQ409',
      rawName: 'Vikramaditya Rao',
      normalizedName: 'vikramaditya rao',
      rawMobile: '9811223344',
      normalizedMobile: '9811223344',
      rawEmail: 'vikram.rao@techcorp.com',
      normalizedEmail: 'vikram.rao@techcorp.com',
      rawPan: 'FGHIJ9999Y',
      normalizedPan: 'FGHIJ9999Y',
      rawDob: '1995-11-20',
      normalizedDob: '1995-11-20',
      rawCity: 'Hyderabad',
      normalizedCity: 'Hyderabad',
      segment: 'Trader',
      balance: 1500000,
      lastActive: '2026-08-11',
    },
    confidence: 28,
    decision: 'pending',
    isDangerousConflict: true,
    conflictReason: 'DANGEROUS CONFLICT: Records share mobile number (9811223344), but have completely conflicting PANs (ABCDE5555X vs FGHIJ9999Y), DOBs (1982-01-15 vs 1995-11-20) and Names (Vikram Malhotra vs Vikramaditya Rao). Hard safety rule prevents auto-merge!',
    evidence: [
      {
        field: 'PAN Number',
        weight: 40,
        valueA: 'ABCDE5555X',
        valueB: 'FGHIJ9999Y',
        result: 'conflict',
        explanation: 'CRITICAL CONFLICT: Explicit PAN mismatch indicates distinct legal entities',
      },
      {
        field: 'Mobile Number',
        weight: 25,
        valueA: '9811223344',
        valueB: '9811223344',
        result: 'match',
        explanation: 'Shared contact number (possible family member / recycled telecom SIM)',
      },
      {
        field: 'Email Address',
        weight: 15,
        valueA: 'vikram.m@domain.com',
        valueB: 'vikram.rao@techcorp.com',
        result: 'conflict',
        explanation: 'Completely different email usernames and domains',
      },
      {
        field: 'Date of Birth',
        weight: 10,
        valueA: '1982-01-15',
        valueB: '1995-11-20',
        result: 'conflict',
        explanation: 'Age gap of 13 years between profiles',
      },
      {
        field: 'Customer Name',
        weight: 7,
        valueA: 'Vikram Malhotra',
        valueB: 'Vikramaditya Rao',
        result: 'partial',
        similarity: 42,
        explanation: 'Jaro-Winkler 42% (Common first prefix only)',
      },
      {
        field: 'City & Location',
        weight: 3,
        valueA: 'Chandigarh',
        valueB: 'Hyderabad',
        result: 'conflict',
        explanation: 'Different geographic states',
      },
    ],
  },
];

export const INITIAL_OPPORTUNITIES: Opportunity[] = [
  {
    id: 'OPP-001',
    goldenId: 'CUST0001',
    customerName: 'Rahul Sharma',
    product: 'wealth',
    score: 91,
    potentialValue: 2000000, // ₹20L
    status: 'new',
    rmId: 'rm1',
    rmName: 'Arjun Mehta',
    createdAt: '2026-08-19T10:00:00Z',
    lastUpdated: '2026-08-19T10:00:00Z',
    reasons: [
      { label: 'Active Direct Equity portfolio holding', value: '₹8.0L', met: true },
      { label: 'Significant Mutual Funds AUM', value: '₹12.0L', met: true },
      { label: 'Zero active Private Wealth mandate', met: true },
      { label: 'Designated HNI customer profile', met: true },
      { label: 'High investment transaction velocity (>3 trades/mo)', met: true },
    ],
  },
  {
    id: 'OPP-002',
    goldenId: 'CUST0001',
    customerName: 'Rahul Sharma',
    product: 'insurance',
    score: 85,
    potentialValue: 120000, // ₹1.2L annual premium
    status: 'new',
    rmId: 'rm1',
    rmName: 'Arjun Mehta',
    createdAt: '2026-08-19T10:15:00Z',
    lastUpdated: '2026-08-19T10:15:00Z',
    reasons: [
      { label: 'Equity holdings qualify (> ₹5L)', value: '₹8.0L', met: true },
      { label: 'Mutual Funds holdings qualify (> ₹5L)', value: '₹12.0L', met: true },
      { label: 'Missing term/health risk coverage in group data', met: true },
      { label: 'High-value customer lifecycle tier', met: true },
    ],
  },
  {
    id: 'OPP-003',
    goldenId: 'CUST0002',
    customerName: 'Priya Patel',
    product: 'loans',
    score: 74,
    potentialValue: 400000, // ₹4L line
    status: 'in_progress',
    rmId: 'rm1',
    rmName: 'Arjun Mehta',
    createdAt: '2026-08-18T11:30:00Z',
    lastUpdated: '2026-08-19T14:10:00Z',
    reasons: [
      { label: 'Mutual fund portfolio eligible for instant LAS credit lien', value: '₹6.5L', met: true },
      { label: 'Clean payment track on term insurance policy', met: true },
      { label: 'No existing retail credit or overdraft product', met: true },
    ],
  },
  {
    id: 'OPP-004',
    goldenId: 'CUST0002',
    customerName: 'Priya Patel',
    product: 'equity',
    score: 68,
    potentialValue: 300000,
    status: 'new',
    rmId: 'rm1',
    rmName: 'Arjun Mehta',
    createdAt: '2026-08-18T14:00:00Z',
    lastUpdated: '2026-08-18T14:00:00Z',
    reasons: [
      { label: 'Regular mutual fund investor in equity oriented schemes', value: '₹6.5L', met: true },
      { label: 'No direct demat trading account opened', met: true },
      { label: 'Affluent customer segment score', met: true },
    ],
  },
  {
    id: 'OPP-005',
    goldenId: 'CUST0004',
    customerName: 'Ananya Sen',
    product: 'loans',
    score: 88,
    potentialValue: 5000000, // ₹50L LAS overdraft
    status: 'new',
    rmId: 'rm2',
    rmName: 'Kavita Rao',
    createdAt: '2026-08-19T08:00:00Z',
    lastUpdated: '2026-08-19T08:00:00Z',
    reasons: [
      { label: 'Massive unencumbered equity & MF portfolio', value: '₹1.05Cr combined', met: true },
      { label: 'Ultra HNI segment rating', met: true },
      { label: 'No active institutional credit line', met: true },
    ],
  },
  {
    id: 'OPP-006',
    goldenId: 'CUST0005',
    customerName: 'Amit Verma',
    product: 'insurance',
    score: 88,
    potentialValue: 250000, // ₹2.5L
    status: 'new',
    rmId: 'rm1',
    rmName: 'Arjun Mehta',
    createdAt: '2026-08-19T09:00:00Z',
    lastUpdated: '2026-08-19T09:00:00Z',
    reasons: [
      { label: 'Equity holdings exceed ₹5L qualification threshold', value: '₹15.0L', met: true },
      { label: 'Mutual Funds holdings exceed ₹5L threshold', value: '₹18.0L', met: true },
      { label: 'Total relationship value exceeds ₹10L standard', value: '₹33.0L', met: true },
      { label: 'No active insurance protection in ecosystem', met: true },
    ],
  },
  {
    id: 'OPP-007',
    goldenId: 'CUST0006',
    customerName: 'Sneha Kapoor',
    product: 'mf',
    score: 79,
    potentialValue: 300000, // ₹3L
    status: 'in_progress',
    rmId: 'rm2',
    rmName: 'Kavita Rao',
    createdAt: '2026-08-18T16:00:00Z',
    lastUpdated: '2026-08-19T11:20:00Z',
    reasons: [
      { label: 'Consistent on-time EMI repayments on Auto Loan', value: '₹12.0L', met: true },
      { label: 'Active term policyholder', met: true },
      { label: 'No investment portfolio setup yet', met: true },
    ],
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'AUD-901',
    timestamp: '2026-08-20T14:32:00Z',
    actorEmail: 'admin@firm.com',
    actorRole: 'admin',
    action: 'CONFIG',
    description: 'Updated Auto-Merge threshold: 80% → 85%, Manual Review floor: 60%',
    metadata: { autoMerge: 85, manualReview: 60 },
  },
  {
    id: 'AUD-902',
    timestamp: '2026-08-20T14:28:00Z',
    actorEmail: 'admin@firm.com',
    actorRole: 'admin',
    action: 'CONFIG',
    description: 'Updated Insurance Cross-sell rule: Minimum Equity balance ₹3L → ₹5L',
    metadata: { ruleId: 'rule-insurance-cross-sell', minEquity: 500000 },
  },
  {
    id: 'AUD-903',
    timestamp: '2026-08-20T13:15:00Z',
    actorEmail: 'rm1@firm.com',
    actorRole: 'rm',
    action: 'MERGE',
    targetId: 'CUST0001',
    description: 'Reviewed candidate records EQ101 + MF501 → Approved manual merge to CUST0001',
    metadata: { confidence: 84, decision: 'approved' },
  },
  {
    id: 'AUD-904',
    timestamp: '2026-08-20T09:15:00Z',
    actorEmail: 'rm1@firm.com',
    actorRole: 'rm',
    action: 'OPP',
    targetId: 'OPP-003',
    description: 'Initiated Loan Against Securities (LAS) opportunity for Priya Patel (CUST0002)',
    metadata: { status: 'in_progress', product: 'loans' },
  },
  {
    id: 'AUD-905',
    timestamp: '2026-08-20T08:45:00Z',
    actorEmail: 'admin@firm.com',
    actorRole: 'admin',
    action: 'OVERRIDE',
    targetId: 'CUST0001',
    description: 'Applied precedence override on Email conflict: Selected Equity source rahul@gmail.com',
    metadata: { field: 'Email Address', precedence: 'equity' },
  },
  {
    id: 'AUD-906',
    timestamp: '2026-08-20T08:00:00Z',
    actorEmail: 'rm1@firm.com',
    actorRole: 'rm',
    action: 'LOGIN',
    description: 'User rm1@firm.com authenticated successfully via 2FA session token',
  },
];
