server:
  port: 8000

spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb+srv://urja2432006_db_user:Yfypax2Rjo2gnEq2@cluster0.wfwuhzi.mongodb.net/customer360?appName=Cluster0}
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

app:
  jwt:
    secret: ${JWT_SECRET:ps04-customer360-dev-secret-key-minimum-256-bit-length-here-123456}
    expiration-ms: 1800000   # 30 minutes
  security:
    max-failed-logins: 5
    lockout-duration-minutes: 30
  source-precedence:
    - EQUITY
    - WEALTH
    - MF
    - INSURANCE
    - LOANS
