import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, Filter, Users, ArrowRight, Shield, Sparkles, CheckCircle2, SlidersHorizontal } from 'lucide-react';
import { useCustomers } from '../hooks/useCustomers';
import { ConfidenceBadge } from '../components/shared/ConfidenceBadge';
import { SourceBadge } from '../components/shared/SourceBadge';
import { MaskedField } from '../components/shared/MaskedField';
import { PaginationBar } from '../components/shared/PaginationBar';
import { formatCurrency } from '../lib/utils';

export const CustomerListPage: React.FC = () => {
  const navigate = useNavigate();
  const [search, setSearch] = useState('');
  const [sourceSystem, setSourceSystem] = useState('');
  const [segment, setSegment] = useState('');
  const [hasOpportunity, setHasOpportunity] = useState(false);
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const { data, isLoading } = useCustomers({
    search,
    sourceSystem: sourceSystem || undefined,
    segment: segment || undefined,
    hasOpportunity: hasOpportunity ? true : undefined,
    page: currentPage,
    limit: pageSize,
  });

  const customers = data?.customers || [];
  const totalRecords = data?.total || customers.length;
  const totalPages = data?.totalPages || Math.ceil(totalRecords / pageSize) || 1;

  return (
    <div className="space-y-5">
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-3 border-b border-[#D8D5CD]">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <h2 className="text-xl font-bold text-[#20252B] uppercase tracking-tight">
              Customer 360 Unified Registry
            </h2>
            <span className="text-xs px-2.5 py-0.5 rounded-md bg-[#EBF1FA] border border-[#BCD1F0] text-[#2457A6] font-mono font-semibold">
              {totalRecords} Golden Records
            </span>
          </div>
          <p className="text-xs text-[#68717C]">
            Deduplicated master customer view generated by deterministic & probabilistic identity resolution across 5 operational business silos.
          </p>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="p-4 rounded-lg bg-[#FFFFFF] border border-[#D8D5CD] shadow-xs space-y-3">
        <div className="grid grid-cols-1 sm:grid-cols-12 gap-3">
          {/* Search Input */}
          <div className="sm:col-span-5 relative">
            <Search className="w-4 h-4 text-[#68717C] absolute left-3 top-1/2 -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search by Name, PAN, Mobile, Golden ID..."
              value={search}
              onChange={(e) => {
                setSearch(e.target.value);
                setCurrentPage(1);
              }}
              className="w-full pl-9 pr-3 py-2 rounded-md bg-[#FFFFFF] border border-[#D8D5CD] text-xs text-[#20252B] placeholder-[#68717C] focus:border-[#2457A6] focus:ring-1 focus:ring-[#2457A6] focus:outline-hidden transition-all"
            />
          </div>

          {/* Source Silo Selector */}
          <div className="sm:col-span-3">
            <select
              value={sourceSystem}
              onChange={(e) => {
                setSourceSystem(e.target.value);
                setCurrentPage(1);
              }}
              className="w-full p-2 rounded-md bg-[#FFFFFF] border border-[#D8D5CD] text-xs text-[#20252B] focus:border-[#2457A6] focus:ring-1 focus:ring-[#2457A6] focus:outline-hidden transition-all"
            >
              <option value="">All Source Silos</option>
              <option value="equity">Equity Brokerage</option>
              <option value="mf">Mutual Funds (CAMS/KFin)</option>
              <option value="insurance">Insurance Shield</option>
              <option value="loans">Credit & Loans</option>
              <option value="wealth">Private Wealth</option>
            </select>
          </div>

          {/* Segment Selector */}
          <div className="sm:col-span-2">
            <select
              value={segment}
              onChange={(e) => {
                setSegment(e.target.value);
                setCurrentPage(1);
              }}
              className="w-full p-2 rounded-md bg-[#FFFFFF] border border-[#D8D5CD] text-xs text-[#20252B] focus:border-[#2457A6] focus:ring-1 focus:ring-[#2457A6] focus:outline-hidden transition-all"
            >
              <option value="">All Segments</option>
              <option value="HNI">HNI Tier</option>
              <option value="Retail">Retail</option>
              <option value="Mass Affluent">Mass Affluent</option>
              <option value="Ultra HNI">Ultra HNI</option>
            </select>
          </div>

          {/* Has Opp Checkbox Toggle */}
          <div className="sm:col-span-2 flex items-center">
            <label className="flex items-center gap-2 text-xs text-[#20252B] cursor-pointer select-none">
              <input
                type="checkbox"
                checked={hasOpportunity}
                onChange={(e) => {
                  setHasOpportunity(e.target.checked);
                  setCurrentPage(1);
                }}
                className="rounded border-[#D8D5CD] text-[#2457A6] focus:ring-0 w-4 h-4 cursor-pointer"
              />
              <span className="truncate font-medium">Has Opportunity</span>
            </label>
          </div>
        </div>
      </div>

      {/* Customer Registry Table */}
      <div className="rounded-lg border border-[#D8D5CD] bg-[#FFFFFF] overflow-hidden shadow-xs">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b border-[#D8D5CD] bg-[#ECEAE4] text-[#68717C] uppercase tracking-wider font-semibold">
                <th className="py-3 px-4 font-mono text-[11px]">Golden ID</th>
                <th className="py-3 px-4 text-[11px]">Customer Name & Segment</th>
                <th className="py-3 px-4 text-[11px]">Unified Identifiers (PII Masked)</th>
                <th className="py-3 px-4 text-[11px]">Linked Sources</th>
                <th className="py-3 px-4 text-right text-[11px]">Relationship Value (TRV)</th>
                <th className="py-3 px-4 text-center text-[11px]">Match Confidence</th>
                <th className="py-3 px-4 text-right text-[11px]">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#D8D5CD] text-[#20252B] font-sans">
              {isLoading ? (
                <tr>
                  <td colSpan={7} className="py-12 text-center text-[#68717C] font-mono">
                    Querying unified customer registry...
                  </td>
                </tr>
              ) : customers.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-12 text-center text-[#68717C]">
                    No customers match the current filter criteria.
                  </td>
                </tr>
              ) : (
                customers.map((cust) => {
                  const sources = cust.sourceSystems || cust.linkedSources || [];
                  const confidence = cust.confidenceScore ?? cust.matchConfidence;
                  return (
                    <tr
                      key={cust.goldenId}
                      id={`customer-row-${cust.goldenId}`}
                      onClick={() => navigate(`/customers/${cust.goldenId}`)}
                      className="hover:bg-[#F4F2ED] transition-colors cursor-pointer group"
                    >
                      {/* Golden ID */}
                      <td className="py-3 px-4 font-mono font-bold text-[#2457A6] whitespace-nowrap">
                        {cust.goldenId}
                      </td>

                      {/* Name & Segment */}
                      <td className="py-3 px-4">
                        <div className="font-bold text-[#20252B] group-hover:text-[#2457A6] transition-colors">
                          {cust.name}
                        </div>
                        <div className="flex items-center gap-1.5 mt-0.5">
                          <span className="text-[10px] font-mono px-1.5 py-0.2 rounded-sm bg-[#ECEAE4] text-[#20252B] border border-[#D8D5CD]">
                            {cust.segment}
                          </span>
                          {cust.riskProfile && (
                            <span className="text-[10px] text-[#68717C]">
                              Risk: {cust.riskProfile}
                            </span>
                          )}
                        </div>
                      </td>

                      {/* Unified Identifiers */}
                      <td className="py-3 px-4">
                        <div className="space-y-1 text-[11px]">
                          <div className="flex items-center gap-1.5">
                            <span className="text-[#68717C] font-mono text-[10px]">PAN:</span>
                            <MaskedField value={cust.pan} type="pan" />
                          </div>
                          <div className="flex items-center gap-1.5">
                            <span className="text-[#68717C] font-mono text-[10px]">MOB:</span>
                            <MaskedField value={cust.mobile} type="mobile" />
                          </div>
                        </div>
                      </td>

                      {/* Linked Sources */}
                      <td className="py-3 px-4">
                        <div className="flex flex-wrap gap-1">
                          {sources.map((s, i) => (
                            <SourceBadge key={i} source={s} size="sm" />
                          ))}
                        </div>
                        <div className="text-[10px] text-[#68717C] mt-1 font-mono">
                          {cust.sourceLineage?.length || sources.length} source records
                        </div>
                      </td>

                      {/* Total Relationship Value */}
                      <td className="py-3 px-4 text-right font-mono font-bold text-[#287A52] text-sm whitespace-nowrap">
                        {formatCurrency(cust.totalRelationshipValue)}
                      </td>

                      {/* Confidence */}
                      <td className="py-3 px-4 text-center whitespace-nowrap">
                        <ConfidenceBadge score={confidence} decision={cust.matchDecision} size="sm" />
                      </td>

                      {/* Action */}
                      <td className="py-3 px-4 text-right whitespace-nowrap">
                        <button
                          id={`view-360-${cust.goldenId}`}
                          onClick={(e) => {
                            e.stopPropagation();
                            navigate(`/customers/${cust.goldenId}`);
                          }}
                          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-md bg-[#EBF1FA] hover:bg-[#2457A6] hover:text-white border border-[#BCD1F0] text-[#2457A6] text-xs font-semibold transition-all cursor-pointer shadow-xs"
                        >
                          <span>View 360</span>
                          <ArrowRight className="w-3.5 h-3.5" />
                        </button>
                      </td>
                    </tr>
                  );
                })
              )}
            </tbody>
          </table>
        </div>

        {/* Integrated Pagination Bar */}
        <PaginationBar
          currentPage={currentPage}
          totalPages={totalPages}
          totalItems={totalRecords}
          pageSize={pageSize}
          onPageChange={setCurrentPage}
          onPageSizeChange={setPageSize}
        />
      </div>
    </div>
  );
};
